### ISSUE TITLE
The road to trajectories

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTIMADE#469]
This issue duplicates #428 and #34. It is meant to be a short checklist of our current agreed path to get "trajectories" into the OPTIMADE standard.

People listed as trajectory stakeholders: @rartino @sauliusg @giovannipizzi @gmrigna @JPBergsma @merkys

Checklist:

- [x] Finalize and merge the latest PR for partial data #467.
- [x] Slightly update and then merge the first version of the metadata proposal #463.
- [x] Make sure that the ongoing PRs related to updating the property definitions #445 defines and supplies the `x-optimade-dimension` keyword for lists. Done.
- [x] Rework / replace the old #452 into a PR that only implements the `property_ranges` query parameters and defines the semantics (`property_ranges=dimname:start:stop:step,dimname2:start:stop:step`) using the dimension names: @JPBergsma has created #481 for this
- [x] Update/rework the trajectories PR #377 to define the entry type/endpoint "trajectories" with actual standardized properties, waiting on action by someone (@JPBergsma ?)

Note: people marked with (*) above "own" the respective PRs and can thus not formally approve them. Nevertheless, since these PRs undergo change requests/discussions, lets try to keep track above when also the owner feels a PR is ok to merge.

Any necessary step I've forgotten? Comment below and I'll edit this list to integrate it.

**Comment by JPBergsma** [comment]
For me, it is not that important that it goes into the 1.2 version. I do not know what Giovanni and Gian-Marco have communicated with you, perhaps they want to have it merged in if it was a deliverable in a proposal. The most important, for me, is that I have a draft version for which everyone agrees on the mechanism that will be used.
I think we should also build a trial implementation before we merge the partial data PR with the 1.2 version, as we now wrote it rather quickly, and I suspect there are still some hidden issues. (I had not finished my review when it got merged.)

I'll start working on the "property_ranges" parameter next week.
It may be better if you message me directly if you want me to do something, as mentions on GitHub can easily get drowned in the large number of messages I get from GitHub.

**Comment by JPBergsma** [comment]
I think we should first make an implementation of the partial data PR. I think it is mainly important that there is a clear draft version, so I and other groups, if they want, can start with implementing it, so we see what is practical and what not.
Whether we make it for version 1.2 depends on when you want to release it. I thought version 1.2 was close to finished. So I think that waiting for a proper implementation may delay the release of 1.2 for several months. For what is the most important for CECAM, I should first consult with Sara and perhaps also Andrea. 
Would it be problematic to release a 1.3 version later on with the trajectory changes and not delay version 1.2 ?

**Comment by gmrigna** [comment]
It would definitely help if you could discuss this with Sara...

**Comment by JPBergsma** [comment]
I have not slept properly for about one and a half week and have therefore not yet been able to finish the PR for the property ranges. I'll try to finish it tomorrow, but I do not know how I will feel by then.

**Comment by orionarcher** [comment]
My team is working on implementing an OPTIMADE-compliant database, and we'd like to include trajectories. I am wondering if including trajectories in the OPTIMADE API is still in scope/development?

**Comment by rartino** [comment]
@orionarcher This is most certainly still in scope and under development. Things are moving a bit slow due to developer overload, but #452 will soon be updated with changes we agreed on during the last monthly meeting.

**Comment by JPBergsma** [comment]
I worked on this until about a year ago.
As far as implementing goes I did quite some work on this before I left. 

See PRs https://github.com/Materials-Consortia/optimade-python-tools/pull/1698
https://github.com/Materials-Consortia/optimade-python-tools/pull/1812
https://github.com/Materials-Consortia/optimade-python-tools/pull/1845
I am however not sure about changes that were made to the specification after I left.
Currently I have a burnout so I am not sure how much time I'll be able to spend on it now.

There was a demo server on Matcloud but unfortunatly it is no longer online.

**Comment by rartino** [comment]
All steps done! 🎉🥳
